#!/bin/bash -x
set -xe

# options include nanostationm2 and w8970
MODEL=$1
TAG="v18.06.1"

if [ -d $MODEL.src ]; then
    cd $MODEL.src
    git pull
else
  git clone --branch ${TAG} --depth 1 https://git.openwrt.org/openwrt/openwrt.git $MODEL.src
  cd $MODEL.src
fi

git checkout ${TAG}

./scripts/feeds update -a
./scripts/feeds install -a

# copy in the config things we care about
cp ../$MODEL.diffconfig .config

# expand to full config
make defconfig

# Build
ionice --class 3 nice -n19 make -j1 #V=s

cp .config .config.$MODEL.$(date --iso)
