#!/bin/bash
set -ex

# options include nanostationm2
MODEL=$1
VERSION=18.06.1
BUILDDIR=/tmp/openwrt-build

if [ ! -d ${BUILDDIR} ] ; then
  mkdir ${BUILDDIR}
fi

case $MODEL in
"f17gw")
  PLATFORM=ar71xx
  TYPE=generic
  TARGET_DEVICE=ar71xx-generic
  PROFILE=tl-wdr4300-v1
  PACKAGES="ipset iptables-mod-conntrack-extra iptables-mod-ipopt luci-app-firewall luci-app-wireguard luci-proto-wireguard wireguard-tools prometheus-node-exporter-lua ddns-scripts luci-app-ddns -dnsmasq dnsmasq-full luci-proto-ipv6 tcpdump-mini curl ip-full uhttpd luci-mod-admin-full luci-theme-bootstrap libiwinfo-lua -wpa-supplicant -wpa-supplicant-mini -wpad-mini wpad -hostapd -hostapd-common -odhcpd-ipv6only curl ca-certificates libustream-openssl watchcat luci-app-watchcat"
  REMOVED_PACKAGES="-dnsmasq -wpa-supplicant -wpa-supplicant-mini -wpad-mini wpad -hostapd -hostapd-common -odhcpd-ipv6only"
;;

"nanostationm2")
  PLATFORM=ar71xx
  TYPE=generic
  TARGET_DEVICE=ar71xx-generic
  PROFILE=ubnt-nano-m
  PACKAGES="odhcp6c prometheus-node-exporter-lua hostapd tcpdump-mini curl ip-tiny luci luci-base luci-theme-bootstrap"
  REMOVED_PACKAGES="-wpad-mini -wpa-supplicant -wpa-supplicant-mini"
;;

"edgerouterx")
  PLATFORM=ramips
  TYPE=mt7621
  TARGET_DEVICE=ramips-mt7621
  PROFILE=ubnt-erx
  PACKAGES="libatomic libnl libnl-core libnl-genl libnl-nf libnl-route libstdcpp uboot-envtools kmod-i2c-gpio-custom kmod-gpio-pca953x luci-base prometheus-node-exporter-lua  adblock luci-app-adblock sqm-scripts sqm-scripts-extra tcpdump-mini curl ip-full ip-bridge luci-mod-admin-full luci-theme-bootstrap luci-mod-admin-full luci-proto-ppp luci-app-firewall luci-app-watchcat luci-proto-wireguard tor tor-geoip kmod-wireguard wireguard-tools wireguard luci-app-wireguard luci-proto-wireguard libustream-openssl bind-host ca-bundle ca-certificates ddns-scripts luci-app-ddns openvpn-openssl kmod-tun lldpd iptables-mod-tee odhcp6c luci-proto-ipv6 dnsmasq-full luci luci-base luci-theme-bootstrap"
  REMOVED_PACKAGES="-dnsmasq -odhcpd"
;;

"ubnt-uap-pro") 
  PLATFORM=ar71xx
  TYPE=generic
  TARGET_DEVICE=ar71xx-generic
  PROFILE=ubnt-uap-pro
  PACKAGES="odhcp6c prometheus-node-exporter-lua hostapd tcpdump-mini curl ip-tiny luci luci-base luci-theme-bootstrap" 
  REMOVED_PACKAGES="-wpad-mini -wpa-supplicant -wpa-supplicant-mini"
;;

"mr33") 
  PLATFORM=ipq40xx
  TYPE=generic
  TARGET_DEVICE=ipq40xx
  PROFILE=meraki_mr33
  PACKAGES="odhcp6c prometheus-node-exporter-lua hostapd tcpdump-mini curl ip-tiny luci luci-base luci-theme-bootstrap" 
  REMOVED_PACKAGES="-wpad-mini -wpa-supplicant -wpa-supplicant-mini"
;;

*)
  echo "specify build target (f17gw ; nanostationm2 ; edgerouterx ; ubnt-uap-pro; mr33)"
  exit 1
;;
esac

# the need for $TYPE and $TARGET_DEVICE seems dumb but it helps get aroudn the problem of downloads        ↓↓↓↓↓↓↓
# http://downloads.openwrt.org/releases/18.06.1/targets/ar71xx/generic/openwrt-imagebuilder-18.06.1-ar71xx-generic.Linux-x86_64.tar.xz
#http://downloads.openwrt.org/releases/18.06.1/targets/ipq40xx/generic/openwrt-imagebuilder-18.06.1-ipq40xx.Linux-x86_64.tar.xz

if [ ! -d ${BUILDDIR}/openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64 ] ; then
  if [ ! -f ${BUILDDIR}/openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64.tar.xz ]; then
    (cd ${BUILDDIR} && curl -O https://downloads.openwrt.org/releases/${VERSION}/targets/${PLATFORM}/${TYPE}/openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64.tar.xz )
  fi
  tar xfJ ${BUILDDIR}/openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64.tar.xz -C ${BUILDDIR}/
fi

COMBINED_PACKAGE_LIST="`echo ${REMOVED_PACKAGES}` `echo ${PACKAGES}`" 

( cd ${BUILDDIR}/openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64 && sudo make image PROFILE="$PROFILE" PACKAGES="$COMBINED_PACKAGE_LIST" )

echo "scp ${BUILDDIR}/openwrt-imagebuilder-${VERSION}-${TARGET_DEVICE}.Linux-x86_64/bin/targets/${PLATFORM}/${TYPE}/openwrt-${VERSION}-${TARGET_DEVICE}-${PROFILE}-squashfs-sysupgrade.bin root@<dest>:/tmp"