#!/bin/sh
set -e # fail if we can't source the file
. ./network-secrets.env 
set -x

case $1 in
  w8970|w8980)
    envsubst \ '
    $trusted_wifikey \
    $dual2_roaming_key \
    $freifunk_roaming_key \
    $henet_tunnelid \
    $henet_username \
    $henet_password \
    $easybell_username \
    $easybell_password \
    $ddns_domain \
    $ddns_username \
    $ddns_password \
    $freifunk_ca_crt \
    $freifunk_client_crt \
    $freifunk_client_key \
    $imagivpn_key \
    $dh2048_pem \
    ' < w8970_w8980.settings  | ssh root@10.7.11.5
    ;;

  repeater0[1-5])
    envsubst \ '
    $trusted_wifikey \
    $dual2_roaming_key \
    $freifunk_roaming_key \
    ' < nanostationm2.settings  | ssh root@$1
    ;;

  *)
    echo "useage: $0 <repeater0X|w8970|w8980>"
  ;;
esac

