#!/bin/sh
set -e # fail if we can't source the file
. ./network-secrets.env 
set -x

case $1 in
  edgerouterx)
    envsubst \ '
    $ddns4_domain \
    $ddns4_username \
    $ddns4_password \
    $ddns6_domain \
    $ddns6_username \
    $ddns6_password \
    $freifunk_ca_crt \
    $freifunk_client_crt \
    $freifunk_client_key \
    $imagivpn_key \
    $wg_vpn_public_key \
    $wg_vpn_private_key \
    $wg_furrow_public_key \
    $wg_furrow_private_key \
    $wg_simonphone_public_key \
    $wg_simonphone_private_key \
    $dh2048_pem \
    ' < edgerouterx.settings  | ssh root@10.7.11.5
    ;;

  n750)
    envsubst \ '
    $trusted_wifikey \
    $dual2_roaming_key \
    $freifunk_roaming_key \
    $henet_tunnelid \
    $henet_username \
    $henet_password \
    $easybell_username \
    $easybell_password \
    $ddns4_domain \
    $ddns4_username \
    $ddns4_password \
    $ddns6_domain \
    $ddns6_username \
    $ddns6_password \
    $freifunk_ca_crt \
    $freifunk_client_crt \
    $freifunk_client_key \
    $imagivpn_key \
    $dh2048_pem \
    ' < n750.settings  | ssh root@10.7.11.5
    ;;

  repeater0[1-6])
    envsubst \ '
    $trusted_wifikey \
    $dual2_roaming_key \
    $freifunk_roaming_key \
    ' < nanostationm2.settings  | ssh root@$1
    ;;

  repeater07)
    envsubst \ '
    $trusted_wifikey \
    $dual2_roaming_key \
    $freifunk_roaming_key \
    ' < mr33.settings  | ssh root@10.7.11.111
    ;;

  *)
    echo "useage: $0 <repeater0X|edgerouterx>"
  ;;
esac

